begin;
select plan(15);
select has_table('public', 'subjects');
select has_table('public', 'annual_subjects');
select has_table('public', 'assessment_types');
select has_table('public', 'grading_formulas');
select has_table('public', 'financial_rules');
select has_table('public', 'academic_year_user_assignments');
select has_column('public', 'annual_subjects', 'coefficient');
select has_column('public', 'annual_subjects', 'weekly_hours');
select has_index('public', 'grading_formulas', 'grading_formulas_one_default_idx');
select has_function('public', 'clone_academic_year_configuration', array['uuid','uuid','boolean','boolean','boolean','boolean','boolean']);
select has_function('public', 'ensure_preparation_year_write');
select ok((select relrowsecurity from pg_catalog.pg_class where oid = 'public.subjects'::regclass), 'RLS active sur les matières');
select ok((select relrowsecurity from pg_catalog.pg_class where oid = 'public.assessment_types'::regclass), 'RLS active sur les évaluations');
select table_privs_are('public', 'financial_rules', 'anon', array[]::text[]);
select function_privs_are('public', 'clone_academic_year_configuration', array['uuid','uuid','boolean','boolean','boolean','boolean','boolean'], 'authenticated', array['EXECUTE']);
select * from finish();
rollback;
