begin;
select plan(15);
select ok(to_regclass('public.subjects') is not null, 'table subjects présente');
select ok(to_regclass('public.annual_subjects') is not null, 'table annual_subjects présente');
select ok(to_regclass('public.assessment_types') is not null, 'table assessment_types présente');
select ok(to_regclass('public.grading_formulas') is not null, 'table grading_formulas présente');
select ok(to_regclass('public.financial_rules') is not null, 'table financial_rules présente');
select ok(to_regclass('public.academic_year_user_assignments') is not null, 'table affectations présente');
select ok(exists(select 1 from information_schema.columns where table_schema = 'public' and table_name = 'annual_subjects' and column_name = 'coefficient'), 'coefficient présent');
select ok(exists(select 1 from information_schema.columns where table_schema = 'public' and table_name = 'annual_subjects' and column_name = 'weekly_hours'), 'volume horaire présent');
select ok(to_regclass('public.grading_formulas_one_default_idx') is not null, 'index formule par défaut présent');
select has_function('public', 'clone_academic_year_configuration', array['uuid','uuid','boolean','boolean','boolean','boolean','boolean']);
select ok(to_regprocedure('public.ensure_preparation_year_write()') is not null, 'fonction de verrouillage présente');
select ok((select relrowsecurity from pg_catalog.pg_class where oid = 'public.subjects'::regclass), 'RLS active sur les matières');
select ok((select relrowsecurity from pg_catalog.pg_class where oid = 'public.assessment_types'::regclass), 'RLS active sur les évaluations');
select table_privs_are('public', 'financial_rules', 'anon', array[]::text[]);
select function_privs_are('public', 'clone_academic_year_configuration', array['uuid','uuid','boolean','boolean','boolean','boolean','boolean'], 'authenticated', array['EXECUTE']);
select * from finish();
rollback;
