import { useCallback, useEffect, useMemo, useState } from "react";
import { Button } from "primereact/button"; import { Column } from "primereact/column"; import { DataTable } from "primereact/datatable"; import { Dialog } from "primereact/dialog"; import { Dropdown } from "primereact/dropdown"; import { InputText } from "primereact/inputtext"; import { Message } from "primereact/message"; import { Tag } from "primereact/tag";
import { PageHeader } from "../../../shared/components/layout/PageHeader"; import { useAcademicSession } from "../../academic-session/components/academic-session-context"; import { generateBulletins, listBatches, listGenerationContext, type BulletinBatchRow } from "../services/bulletins.service";

export function BulletinGenerationsPage() { const { institutionId, yearId, year } = useAcademicSession(); const [rows,setRows]=useState<BulletinBatchRow[]>([]); const [periods,setPeriods]=useState<{id:string;name:string}[]>([]); const [classes,setClasses]=useState<{id:string;name:string}[]>([]); const [query,setQuery]=useState(""); const [open,setOpen]=useState(false); const [periodId,setPeriodId]=useState(""); const [classId,setClassId]=useState(""); const [loading,setLoading]=useState(false); const [error,setError]=useState(""); const [notice,setNotice]=useState("");
  const load=useCallback(async()=>{if(!yearId)return; setLoading(true); try { const [items,context]=await Promise.all([listBatches(institutionId,yearId),listGenerationContext(institutionId,yearId)]); setRows(items); setPeriods(context.periods); setClasses(context.classes); } catch {setError("Impossible de charger les générations.");} finally{setLoading(false);}},[institutionId,yearId]); useEffect(()=>{void load();},[load]);
  const filtered=useMemo(()=>rows.filter((r)=>JSON.stringify(r).toLowerCase().includes(query.toLowerCase())),[query,rows]); async function submit(){if(!yearId||!periodId)return;setLoading(true);setError("");try{const result=await generateBulletins({institutionId,yearId,periodId,classId:classId||undefined});setNotice(`${result.generated} bulletin(s) généré(s), ${result.blocked} bloqué(s).`);setOpen(false);await load();}catch{setError("La génération a échoué. Vérifiez les affectations, notes et résultats reportés.");}finally{setLoading(false);}}
  if(!yearId)return <Message severity="warn" text="Sélectionnez une année scolaire."/>; return <div className="space-y-4 pb-8"><PageHeader eyebrow="Notes & Bulletins" title="Générations" description={`Préparer et contrôler les lots de bulletins · ${year?.name??"Année"}`} actions={<Button label="Générer des bulletins" icon="pi pi-sparkles" onClick={()=>setOpen(true)}/>}/>{error?<Message severity="error" text={error}/>:null}{notice?<Message severity="success" text={notice}/>:null}<section className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><span className="p-input-icon-left block max-w-xl"><i className="pi pi-search"/><InputText value={query} onChange={(e)=>setQuery(e.target.value)} placeholder="Rechercher une période ou une portée" className="h-11 w-full rounded-xl pl-9"/></span></section><section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><DataTable value={filtered} loading={loading} dataKey="id" stripedRows paginator rows={10} emptyMessage="Aucun lot de génération"><Column field="createdAt" header="Date" body={(r:BulletinBatchRow)=>new Date(r.createdAt).toLocaleString("fr-FR")}/><Column field="periodName" header="Période"/><Column field="scope" header="Portée"/><Column field="total" header="Élèves"/><Column field="generated" header="Générés"/><Column field="blocked" header="Bloqués"/><Column header="État" body={(r:BulletinBatchRow)=><Tag value={r.status} severity={r.status==="completed"?"success":r.status==="failed"?"danger":"warning"}/>} /></DataTable></section><Dialog header="Générer les bulletins" visible={open} modal className="w-[min(94vw,34rem)]" onHide={()=>setOpen(false)}><div className="space-y-4"><Message severity="info" text="La période appartient au cycle de la classe. Les résultats reportés bloquent le bulletin concerné."/><label className="field"><span>Période *</span><Dropdown value={periodId} options={periods.map(p=>({label:p.name,value:p.id}))} onChange={(e)=>setPeriodId(String(e.value))} className="w-full" placeholder="Choisir la période"/></label><label className="field"><span>Classe (facultatif)</span><Dropdown value={classId} options={classes.map(c=>({label:c.name,value:c.id}))} showClear onChange={(e)=>setClassId(typeof e.value==="string"?e.value:"")} className="w-full" placeholder="Tout l’établissement"/></label><div className="flex justify-end gap-2"><Button label="Annuler" severity="secondary" outlined onClick={()=>setOpen(false)}/><Button label="Lancer la génération" icon="pi pi-play" loading={loading} disabled={!periodId} onClick={()=>void submit()}/></div></div></Dialog></div>;
}
