import { useCallback, useEffect, useState } from "react";
import { useLocation, useNavigate } from "react-router-dom";
import { Button } from "primereact/button";
import { Column } from "primereact/column";
import { DataTable, type DataTablePageEvent } from "primereact/datatable";
import { Message } from "primereact/message";
import { Tag } from "primereact/tag";
import { PageHeader } from "../../../shared/components/layout/PageHeader";
import { useAcademicSession } from "../../academic-session/components/academic-session-context";
import { NotesDataTableToolbar } from "../components/NotesDataTableToolbar";
import { listOperationsContext, listOperationsPage, type AppreciationItem, type AverageControlItem, type OperationsMode, type PostponedResultItem } from "../services/notes-operations.service";
type Row = PostponedResultItem | AppreciationItem | AverageControlItem;
export function NotesOperationsPage() {
  const { pathname } = useLocation(); const navigate = useNavigate(); const { institutionId, yearId, year } = useAcademicSession();
  const mode: OperationsMode = pathname.endsWith("appreciations") ? "appreciations" : pathname.endsWith("controle-moyennes") ? "averages" : "postponed";
  const [items, setItems] = useState<Row[]>([]); const [total, setTotal] = useState(0); const [first, setFirst] = useState(0); const [pageSize, setPageSize] = useState(10); const [query, setQuery] = useState(""); const [classId, setClassId] = useState(""); const [periodId, setPeriodId] = useState(""); const [state, setState] = useState(""); const [advanced, setAdvanced] = useState(false); const [classes, setClasses] = useState<{id:string;name:string}[]>([]); const [periods, setPeriods] = useState<{id:string;name:string}[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const load = useCallback(async () => { if (!yearId) return; setLoading(true); try { const [page, context] = await Promise.all([listOperationsPage(institutionId, yearId, mode, { first, rows: pageSize, search: query, classId, periodId, state }), listOperationsContext(institutionId, yearId)]); setItems(page.rows); setTotal(page.total); setClasses(context.classes); setPeriods(context.periods); } catch { setError("Impossible de charger les données pédagogiques."); } finally { setLoading(false); } }, [classId, first, institutionId, mode, pageSize, periodId, query, state, yearId]);
  useEffect(() => { const timer = setTimeout(() => void load(), 250); return () => clearTimeout(timer); }, [load]);
  const config = mode === "appreciations" ? ["Appréciations", "Les commentaires pédagogiques saisis par matière apparaîtront sur le bulletin de l’élève."] : mode === "averages" ? ["Contrôle des moyennes", "Vérifiez les cahiers prêts et les blocages avant de générer les bulletins."] : ["Rattrapages à compléter", "Complétez les évaluations temporairement reportées : elles bloquent la moyenne et le bulletin."];
  const reset = () => { setQuery(""); setClassId(""); setPeriodId(""); setState(""); setFirst(0); };
  if (!yearId) return <Message severity="warn" text="Sélectionnez une année scolaire." />;
  return <div className="space-y-4 pb-8"><PageHeader eyebrow="Notes & Bulletins" title={config[0]} description={`${config[1]} · ${year?.name ?? "Année"}`} actions={<Button label="Actualiser" icon="pi pi-refresh" severity="secondary" outlined onClick={() => void load()} />} />{error ? <Message severity="error" text={error} /> : null}<NotesDataTableToolbar search={query} onSearch={(v) => { setFirst(0); setQuery(v); }} advanced={advanced} onAdvanced={() => setAdvanced((v) => !v)} onReset={reset} activeCount={[query,classId,periodId,state].filter(Boolean).length} status={state} onStatus={mode === "averages" ? (v) => { setFirst(0); setState(v); } : undefined} statusOptions={[{label:"Prêt",value:"ready"},{label:"Bloqué",value:"incomplete"},{label:"À démarrer",value:"not_started"}]} classId={classId} onClass={(v) => { setFirst(0); setClassId(v); }} classOptions={classes.map((i) => ({label:i.name,value:i.id}))} periodId={periodId} onPeriod={mode === "averages" ? undefined : (v) => { setFirst(0); setPeriodId(v); }} periodOptions={periods.map((i) => ({label:i.name,value:i.id}))} placeholder="Élève, matricule ou enseignant" /><section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><DataTable value={items} lazy loading={loading} paginator first={first} rows={pageSize} totalRecords={total} rowsPerPageOptions={[10,25,50]} onPage={(e: DataTablePageEvent) => { setFirst(e.first); setPageSize(e.rows); }} dataKey="id" stripedRows emptyMessage="Aucun élément trouvé">{mode === "postponed" ? <><Column field="studentName" header="Élève" /><Column field="className" header="Classe" /><Column field="subjectName" header="Matière" /><Column field="noteLabel" header="Note" /><Column header="Impact" body={(r: PostponedResultItem) => <Tag value={r.impact} severity="warning" />} /><Column header="Action" body={() => <Button label="Compléter" text onClick={() => void navigate("/notes-bulletins/cahiers")} />} /></> : mode === "appreciations" ? <><Column field="studentName" header="Élève" /><Column field="className" header="Classe" /><Column field="subjectName" header="Matière" /><Column field="appreciation" header="Appréciation" /><Column field="updatedAt" header="Mise à jour" /></> : <><Column field="className" header="Classe" /><Column field="subjectName" header="Matière" /><Column field="teacherName" header="Enseignant" /><Column field="coefficient" header="Coefficient" /><Column field="notesCount" header="Notes" /><Column header="État" body={(r: AverageControlItem) => <Tag value={r.state === "ready" ? "Prêt" : r.state === "incomplete" ? "Bloqué" : "À démarrer"} severity={r.state === "ready" ? "success" : "warning"} />} /><Column header="Action" body={() => <Button label="Ouvrir le cahier" text onClick={() => void navigate("/notes-bulletins/cahiers")} />} /></>}</DataTable></section></div>;
}
