import { useCallback, useEffect, useMemo, useState } from "react";
import { Button } from "primereact/button"; import { Column } from "primereact/column"; import { DataTable } from "primereact/datatable"; import { Dialog } from "primereact/dialog"; import { Dropdown } from "primereact/dropdown"; import { InputText } from "primereact/inputtext"; import { Tag } from "primereact/tag";
import { PageHeader } from "../../../shared/components/layout/PageHeader"; import { useAcademicSession } from "../../academic-session/components/academic-session-context"; import { useToast } from "../../../shared/components/toast-context";
import type { Employee, EmployeeStatus } from "../domain/personnel"; import { employeeStatusLabels } from "../domain/personnel"; import { createEmployee, listEmployees } from "../services/personnel.service";

const empty = { first_name: "", last_name: "", phone: "", email: "", employee_number: "" };
export function EmployeesPage() { const { institutionId } = useAcademicSession(); const notify = useToast(); const [items,setItems]=useState<Employee[]>([]); const [search,setSearch]=useState(""); const [status,setStatus]=useState<EmployeeStatus>(); const [open,setOpen]=useState(false); const [form,setForm]=useState(empty); const [saving,setSaving]=useState(false);
  const load=useCallback(async()=>setItems(await listEmployees(institutionId)),[institutionId]); useEffect(()=>{void load();},[load]);
  const filtered=useMemo(()=>items.filter(x=>(!status||x.status===status)&&`${x.first_name} ${x.last_name} ${x.employee_number}`.toLowerCase().includes(search.toLowerCase())),[items,search,status]);
  const save=async()=>{setSaving(true);try{await createEmployee({institution_id:institutionId,...form,status:"active",hired_on:new Date().toISOString().slice(0,10)});setOpen(false);setForm(empty);await load();notify({severity:"success",summary:"Employé créé"});}catch(e){notify({severity:"error",summary:"Création impossible",detail:e instanceof Error?e.message:undefined});}finally{setSaving(false)}};
  return <div className="space-y-4 pb-8"><PageHeader title="Personnel" description="Employés, fonctions, contrats et accès." actions={<Button label="Ajouter un employé" icon="pi pi-plus" onClick={()=>setOpen(true)}/>}/><section className="flex flex-col gap-3 rounded-2xl border border-slate-200 bg-white p-4 shadow-sm md:flex-row"><span className="p-input-icon-left flex-1"><i className="pi pi-search"/><InputText className="w-full" value={search} placeholder="Nom ou matricule" onChange={e=>setSearch(e.target.value)}/></span><Dropdown className="w-full md:w-56" value={status} showClear placeholder="Tous les états" options={Object.entries(employeeStatusLabels).map(([value,label])=>({value,label}))} onChange={e=>setStatus(e.value)}/></section><section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><DataTable value={filtered} dataKey="id" paginator rows={10} emptyMessage="Aucun employé"><Column header="Employé" body={(x:Employee)=><div><strong>{x.first_name} {x.last_name}</strong><small className="block text-slate-500">{x.employee_number}</small></div>}/><Column field="phone" header="Téléphone"/><Column field="email" header="E-mail"/><Column header="État" body={(x:Employee)=><Tag value={employeeStatusLabels[x.status]} severity={x.status==="active"?"success":x.status==="suspended"?"warning":"secondary"}/>} /><Column header="Accès" body={(x:Employee)=><Tag value={x.membership_id?"Compte lié":"Sans accès"} severity={x.membership_id?"info":"secondary"}/>} /></DataTable></section><Dialog header="Nouvel employé" visible={open} className="w-[min(94vw,40rem)]" onHide={()=>setOpen(false)}><div className="grid gap-3 sm:grid-cols-2">{[["first_name","Prénoms"],["last_name","Nom"],["employee_number","Matricule"],["phone","Téléphone"],["email","E-mail"]].map(([key,label])=><label key={key}><span className="mb-1 block text-sm font-medium">{label}</span><InputText className="w-full" value={form[key as keyof typeof form]} onChange={e=>setForm({...form,[key]:e.target.value})}/></label>)}</div><div className="mt-5 flex justify-end gap-2"><Button label="Annuler" severity="secondary" outlined onClick={()=>setOpen(false)}/><Button label="Créer" loading={saving} disabled={!form.first_name||!form.last_name||!form.employee_number} onClick={()=>void save()}/></div></Dialog></div> }
